---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags: nginx

- name: Copy Nginx config
  copy:
    src: default.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx
  tags: nginx
