---
- name: Install npm packages
  become: true
  shell: |
    . {{ home_dir }}/.nvm/nvm.sh
    npm install
  args:
    chdir: "{{ app_work_dir }}"
  environment:
    NVM_DIR: "{{ home_dir }}/.nvm"
  tags:
    - npm

- name: Ensure the app directory exists and has correct permissions
  file:
    path: "{{ app_work_dir }}"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    recurse: yes
