# ---
# - name: Create MySQL database
#   mysql_db:
#     name: "{{ db_name }}"
#     state: present
#   tags:
#     - mysql
#     - create-db
# # - name: Create MySQL database
# #   community.mysql.mysql_db:
# #     name: "{{ db_name }}"
# #     state: present
# #     login_unix_socket: /run/mysqld/mysqld.sock
# #     tags:
# #       - mysql
# #       - create-db
