# - name: Installing Mysql
#   apt: name={{item}} state=present
#   become: true
#   with_items:
#     - python3
#     - python3-setuptools
#     - python3-dev
#     - build-essential
#     - python3-pip
#     - python3-mysqldb

# - name: Install mysql components
#   apt: name={{item}} state=present
#   become: true
#   with_items:
#     - mysql-server
#     - mysql-client
