---
- name: Update apt packages
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags: common

- name: Install common packages
  apt:
    name: 
      - curl
      - git
      - unzip
      - software-properties-common
    state: present
  tags: common
